[package]
name = "pycompiler"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
anyhow = "1.0.86"
rustpython-parser = "0.4.0"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }